// Package v2 Code generated by swaggo/swag. DO NOT EDIT
package v2

import "github.com/swaggo/swag"

const docTemplatev2 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/portfolios/{portfolioCode}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve one portfolio by its business code (Portfolio V2).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "Get Portfolio By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PortfolioResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{portfolioCode}/cash": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List cash balances by currency for a portfolio, resolved by business code (Portfolio V2).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "Get Portfolio Cash Balances By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CashBalanceResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{portfolioCode}/holdings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List current holdings for a portfolio, resolved by business code (Portfolio V2).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "Get Portfolio Holdings By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HoldingResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{portfolioCode}/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List transactions for a portfolio with optional instrument and date filters, resolved by business code (Portfolio V2).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "List Portfolio Transactions By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Instrument UUID",
                        "name": "instrument_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start business date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End business date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TransactionListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Post a buy, sell, cash, or other portfolio transaction into the ledger, resolved by business code (Portfolio V2). Request body must not include fund_id or contract_id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "Post Portfolio Transaction By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transaction post payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/PostTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{portfolioCode}/transactions/simulate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Run the post preconditions and pre-trade compliance checks, then preview ledger cash and position impact without mutating investment tables, resolved by business code (Portfolio V2).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "Simulate Portfolio Transaction By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transaction simulation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/PostTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/TransactionSimulationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{portfolioCode}/transactions/{transactionId}/reverse": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Post a reversal transaction for an existing portfolio transaction, resolved by business code (Portfolio V2).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "Reverse Portfolio Transaction By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transaction UUID",
                        "name": "transactionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transaction reversal payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ReverseTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{portfolioCode}/valuations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List valuation snapshots for a portfolio, resolved by business code (Portfolio V2).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "List Portfolio Valuations By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ValuationListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/portfolios/{portfolioCode}/valuations/latest": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the latest internal valuation snapshot for a portfolio, resolved by business code (Portfolio V2).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Investment - Portfolios V2"
                ],
                "summary": "Get Latest Portfolio Valuation By Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Portfolio code",
                        "name": "portfolioCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ValuationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CashBalanceResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "last_business_date": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "CashProjectionResponse": {
            "type": "object",
            "properties": {
                "cash_impact": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "current_balance": {
                    "type": "string"
                },
                "projected_balance": {
                    "type": "string"
                }
            }
        },
        "ComplianceBreachPreviewResponse": {
            "type": "object",
            "properties": {
                "breach_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "overridable": {
                    "type": "boolean"
                },
                "rule_type_id": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "verdict": {
                    "type": "string"
                }
            }
        },
        "CompliancePreviewResponse": {
            "type": "object",
            "properties": {
                "breaches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ComplianceBreachPreviewResponse"
                    }
                },
                "check_group_id": {
                    "type": "string"
                },
                "rules_evaluated": {
                    "type": "integer"
                },
                "verdict": {
                    "type": "string"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "HoldingResponse": {
            "type": "object",
            "properties": {
                "average_cost": {
                    "type": "string"
                },
                "cost_basis": {
                    "type": "string"
                },
                "instrument_id": {
                    "type": "string"
                },
                "last_business_date": {
                    "type": "string"
                },
                "last_transaction_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "PortfolioResponse": {
            "type": "object",
            "properties": {
                "base_currency": {
                    "type": "string"
                },
                "benchmark": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fund_id": {
                    "type": "string"
                },
                "has_units": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "inception_date": {
                    "type": "string"
                },
                "manager_user_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "risk_profile": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "strategy_code": {
                    "type": "string"
                },
                "style_id": {
                    "type": "string"
                },
                "tax_lot_method": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "valuation_currency": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "PositionProjectionResponse": {
            "type": "object",
            "properties": {
                "current_average_cost": {
                    "type": "string"
                },
                "current_cost_basis": {
                    "type": "string"
                },
                "current_quantity": {
                    "type": "string"
                },
                "instrument_id": {
                    "type": "string"
                },
                "projected_average_cost": {
                    "type": "string"
                },
                "projected_cost_basis": {
                    "type": "string"
                },
                "projected_quantity": {
                    "type": "string"
                }
            }
        },
        "PostTransactionRequest": {
            "type": "object",
            "required": [
                "business_date",
                "currency",
                "transaction_type"
            ],
            "properties": {
                "business_date": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "fees": {
                    "type": "string"
                },
                "force_post": {
                    "type": "boolean"
                },
                "fx_rate_to_base": {
                    "type": "string"
                },
                "gross_amount": {
                    "type": "string"
                },
                "instrument_id": {
                    "type": "string"
                },
                "net_amount": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "settlement_date": {
                    "type": "string"
                },
                "side": {
                    "type": "string"
                },
                "source_decision_id": {
                    "type": "string"
                },
                "source_execution_id": {
                    "type": "string"
                },
                "transaction_type": {
                    "type": "string"
                }
            }
        },
        "ReverseTransactionRequest": {
            "type": "object",
            "required": [
                "business_date",
                "reason"
            ],
            "properties": {
                "business_date": {
                    "type": "string"
                },
                "force_post": {
                    "type": "boolean"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "TransactionListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TransactionResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "TransactionResponse": {
            "type": "object",
            "properties": {
                "business_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "fees": {
                    "type": "string"
                },
                "fund_id": {
                    "type": "string"
                },
                "fx_rate_to_base": {
                    "type": "string"
                },
                "gross_amount": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instrument_id": {
                    "type": "string"
                },
                "net_amount": {
                    "type": "string"
                },
                "portfolio_id": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "reverses_transaction_id": {
                    "type": "string"
                },
                "settlement_date": {
                    "type": "string"
                },
                "side": {
                    "type": "string"
                },
                "source_decision_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "transaction_type": {
                    "type": "string"
                }
            }
        },
        "TransactionSimulationResponse": {
            "type": "object",
            "properties": {
                "cash": {
                    "$ref": "#/definitions/CashProjectionResponse"
                },
                "compliance": {
                    "$ref": "#/definitions/CompliancePreviewResponse"
                },
                "gross_amount": {
                    "type": "string"
                },
                "instrument_id": {
                    "type": "string"
                },
                "net_amount": {
                    "type": "string"
                },
                "portfolio_id": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/PositionProjectionResponse"
                },
                "transaction_type": {
                    "type": "string"
                }
            }
        },
        "ValuationLineResponse": {
            "type": "object",
            "properties": {
                "cost_basis": {
                    "type": "string"
                },
                "fx_rate_to_valuation_ccy": {
                    "type": "string"
                },
                "instrument_id": {
                    "type": "string"
                },
                "is_stale": {
                    "type": "boolean"
                },
                "market_value": {
                    "type": "string"
                },
                "price_in_quote_ccy": {
                    "type": "string"
                },
                "price_snapshot_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                },
                "quote_currency": {
                    "type": "string"
                },
                "unrealised_pnl": {
                    "type": "string"
                }
            }
        },
        "ValuationListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ValuationResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "ValuationResponse": {
            "type": "object",
            "properties": {
                "aum": {
                    "type": "string"
                },
                "business_date": {
                    "type": "string"
                },
                "cash_balance": {
                    "type": "string"
                },
                "cost_basis": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "has_stale_inputs": {
                    "type": "boolean"
                },
                "holding_lines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ValuationLineResponse"
                    }
                },
                "id": {
                    "type": "string"
                },
                "is_indicative": {
                    "type": "boolean"
                },
                "market_value": {
                    "type": "string"
                },
                "portfolio_id": {
                    "type": "string"
                },
                "price_set_hash": {
                    "type": "string"
                },
                "realised_pnl": {
                    "type": "string"
                },
                "roi": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "unrealised_pnl": {
                    "type": "string"
                },
                "valuation_ccy": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Bearer Token. Format: \"Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfov2 holds exported Swagger Info so clients can modify it
var SwaggerInfov2 = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v2",
	Schemes:          []string{"http", "https"},
	Title:            "IMS Thailand API — Portfolio V2",
	Description:      "Portfolio V2 endpoints (docs/api/portfolio-v2-api-ddd.md), mounted under /api/v2.",
	InfoInstanceName: "v2",
	SwaggerTemplate:  docTemplatev2,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov2.InstanceName(), SwaggerInfov2)
}
