info:
  name: delete-team-member
  type: http
  seq: 9

http:
  method: DELETE
  url: "{{approval-config-base-url}}/teams/:teamId/members/:memberId"
  params:
    - name: teamId
      value: "{{approval-team-id}}"
      type: path
    - name: memberId
      value: "{{approval-team-member-id}}"
      type: path
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
