info:
  name: list-teams
  type: http
  seq: 1

http:
  method: GET
  url: "{{approval-config-base-url}}/teams"
  auth:
    type: bearer
    token: "{{token}}"

runtime:
  scripts:
    - type: after-response
      code: |-
        const body = res.getBody();
        const rows = Array.isArray(body?.data) ? body.data : [];
        const first = rows[0] || {};

        if (first.id) {
          bru.setEnvVar("approval-team-id", first.id, { persist: true });
        }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
