import type {
  DataPermissionGrant,
  FunctionPermissionRow,
  NotificationPreference,
  PermissionActionColumn,
  SecurityPolicyModel,
  SettingsApiCapability,
  SettingsGroupRole,
} from "../ui.types";

export const SETTINGS_PERMISSION_ACTIONS: PermissionActionColumn[] = [
  { key: "view", label: "View" },
  { key: "search", label: "Search" },
  { key: "add", label: "Add" },
  { key: "edit", label: "Edit" },
  { key: "delete", label: "Delete" },
  { key: "approve", label: "Approve" },
  { key: "revokeApproval", label: "Revoke approval" },
  { key: "export", label: "Export" },
  { key: "settings", label: "Settings" },
];

export const SETTINGS_API_CAPABILITIES: SettingsApiCapability[] = [
  {
    id: "personal-account",
    label: "Personal account",
    capability: "Read own profile, change own password, read MFA status, list and revoke own sessions",
    status: "live",
  },
  {
    id: "users",
    label: "Other accounts",
    capability: "List, create, enable, disable, lock, unlock, reset passwords",
    status: "live",
  },
  {
    id: "sessions",
    label: "User sessions",
    capability: "List and revoke active sessions for selected users",
    status: "live",
  },
  {
    id: "audit",
    label: "Audit / Change logs",
    capability: "Filter IAM audit events and export CSV evidence",
    status: "live",
  },
  {
    id: "groups",
    label: "Groups / Roles",
    capability: "Derived from current user directory payload",
    status: "read-only",
  },
  {
    id: "permissions",
    label: "Function and data permissions",
    capability: "Backend administration endpoints are not exposed in this frontend",
    status: "not-exposed",
  },
  {
    id: "policy",
    label: "Security policy / Notifications",
    capability: "Displayed as typed configuration scaffolds until APIs exist",
    status: "not-exposed",
  },
];

export const SETTINGS_DEMO_GROUPS: SettingsGroupRole[] = [
  {
    id: "portfolio-managers",
    name: "Portfolio Managers",
    description: "Investment decision users responsible for model portfolios and order intent.",
    source: "demo",
    membersCount: 0,
    responsibilities: ["Investment decision", "Portfolio review", "Watchlist monitoring"],
    permissionFamilies: ["INVESTMENT_VIEW", "INVESTMENT_CREATE", "APPROVAL_VIEW"],
    dataScopes: ["Managed portfolios", "Assigned contracts"],
    riskLevel: "elevated",
  },
  {
    id: "operations-control",
    name: "Operations Control",
    description: "Middle-office operators for workflow follow-up and exception handling.",
    source: "demo",
    membersCount: 0,
    responsibilities: ["Workflow monitoring", "Execution support", "Daily controls"],
    permissionFamilies: ["WORKFLOW_VIEW", "INVESTMENT_VIEW", "AUDIT_VIEW"],
    dataScopes: ["Operational queues", "Execution records"],
    riskLevel: "standard",
  },
  {
    id: "iam-admin",
    name: "IAM Administrators",
    description: "Privileged administrators for accounts, access state, and audit evidence.",
    source: "demo",
    membersCount: 0,
    responsibilities: ["Account lifecycle", "Security reviews", "Audit export"],
    permissionFamilies: ["IAM_USER_VIEW", "IAM_USER_UPDATE", "IAM_AUDIT_VIEW"],
    dataScopes: ["Identity directory", "IAM audit trail"],
    riskLevel: "restricted",
  },
];

export const SETTINGS_FUNCTION_PERMISSION_ROWS: FunctionPermissionRow[] = [
  {
    id: "dashboard",
    menu: "Dashboard",
    functionName: "Executive overview",
    owner: "Investment operations",
    status: "demo",
    permissions: {
      view: true,
      search: false,
      add: false,
      edit: false,
      delete: false,
      approve: false,
      revokeApproval: false,
      export: false,
      settings: false,
    },
  },
  {
    id: "investment-decision",
    menu: "Investment",
    functionName: "Decision workbench",
    owner: "Front office",
    status: "demo",
    permissions: {
      view: true,
      search: true,
      add: true,
      edit: true,
      delete: false,
      approve: false,
      revokeApproval: false,
      export: true,
      settings: false,
    },
  },
  {
    id: "approval",
    menu: "Approval",
    functionName: "Approval queues",
    owner: "Risk and compliance",
    status: "demo",
    permissions: {
      view: true,
      search: true,
      add: false,
      edit: false,
      delete: false,
      approve: true,
      revokeApproval: true,
      export: true,
      settings: false,
    },
  },
  {
    id: "workflow",
    menu: "Workflow",
    functionName: "Operational workflow",
    owner: "Middle office",
    status: "demo",
    permissions: {
      view: true,
      search: true,
      add: false,
      edit: true,
      delete: false,
      approve: false,
      revokeApproval: false,
      export: true,
      settings: false,
    },
  },
  {
    id: "iam",
    menu: "Settings",
    functionName: "IAM administration",
    owner: "Security administration",
    status: "demo",
    permissions: {
      view: true,
      search: true,
      add: true,
      edit: true,
      delete: false,
      approve: false,
      revokeApproval: false,
      export: true,
      settings: true,
    },
  },
];

export const SETTINGS_DEMO_DATA_GRANTS: DataPermissionGrant[] = [
  {
    id: "grant-balanced-income",
    user: "portfolio.manager",
    userLabel: "Portfolio Manager",
    contractId: "TH-FUND-001",
    contractName: "Thai Balanced Income Fund",
    scope: "Selected funds",
    source: "demo",
    updatedAt: "2026-03-12T10:40:00+07:00",
  },
  {
    id: "grant-equity-growth",
    user: "risk.reviewer",
    userLabel: "Risk Reviewer",
    contractId: "TH-FUND-014",
    contractName: "Equity Growth Mandate",
    scope: "Read only",
    source: "demo",
    updatedAt: "2026-03-14T09:12:00+07:00",
  },
  {
    id: "grant-institutional-fixed-income",
    user: "ops.control",
    userLabel: "Operations Control",
    contractId: "TH-MANDATE-022",
    contractName: "Institutional Fixed Income Mandate",
    scope: "All funds",
    source: "demo",
    updatedAt: "2026-03-15T16:30:00+07:00",
  },
];

export const SETTINGS_SECURITY_POLICY: SecurityPolicyModel = {
  authMode: "Internal",
  source: "demo",
  settings: [
    {
      id: "minimum-length",
      label: "Minimum length",
      value: 12,
      unit: "characters",
      helper: "Temporary and reset passwords must satisfy this floor.",
    },
    {
      id: "expiry-days",
      label: "Password expiry",
      value: 90,
      unit: "days",
      helper: "Rotation interval for internal password mode.",
    },
    {
      id: "reuse",
      label: "Reuse restriction",
      value: 6,
      unit: "previous passwords",
      helper: "Prevents users from cycling recent credentials.",
    },
    {
      id: "failed-attempts",
      label: "Max failed login attempts",
      value: 5,
      helper: "Account locks after this threshold.",
    },
    {
      id: "change-interval",
      label: "Minimum change interval",
      value: 1,
      unit: "day",
      helper: "Limits rapid password churn after a successful change.",
    },
    {
      id: "enforce-rule",
      label: "Enforce password rule",
      value: true,
      helper: "Applies complexity and history validation to all internal accounts.",
    },
  ],
};

export const SETTINGS_NOTIFICATION_PREFERENCES: NotificationPreference[] = [
  {
    id: "account-lock",
    event: "Account locked",
    audience: "IAM administrators",
    channels: ["In-app", "Email"],
    severity: "High",
    enabled: true,
    source: "demo",
  },
  {
    id: "password-reset",
    event: "Password reset completed",
    audience: "Security administrators",
    channels: ["In-app"],
    severity: "Medium",
    enabled: true,
    source: "demo",
  },
  {
    id: "audit-export",
    event: "Audit export requested",
    audience: "Auditors",
    channels: ["In-app", "Email"],
    severity: "High",
    enabled: true,
    source: "demo",
  },
  {
    id: "permission-review",
    event: "Permission review due",
    audience: "Group owners",
    channels: ["In-app"],
    severity: "Medium",
    enabled: false,
    source: "demo",
  },
];
