-- Phase 0 reference data: ISO-3166-1 alpha-2 countries.
--
-- Source: ISO-3166-1 standard, alpha-2 / alpha-3 / numeric codes plus the
-- short English country name. Region mapping is the project's geographic
-- bucket: TH is pinned to THAILAND for domestic-scope queries; every other
-- country resolves to APAC, EMEA, or AMER. The cross-cutting buckets
-- (GLOBAL, EMERGING, DEVELOPED) are populated at the fund / instrument layer
-- in a later phase.

INSERT INTO investment__countries (code, alpha3, numeric_code, name, region_code, is_active) VALUES
    ('AD', 'AND', '020', 'Andorra',                                  'EMEA', true),
    ('AE', 'ARE', '784', 'United Arab Emirates',                     'EMEA', true),
    ('AF', 'AFG', '004', 'Afghanistan',                              'APAC', true),
    ('AG', 'ATG', '028', 'Antigua and Barbuda',                      'AMER', true),
    ('AI', 'AIA', '660', 'Anguilla',                                 'AMER', true),
    ('AL', 'ALB', '008', 'Albania',                                  'EMEA', true),
    ('AM', 'ARM', '051', 'Armenia',                                  'EMEA', true),
    ('AO', 'AGO', '024', 'Angola',                                   'EMEA', true),
    ('AQ', 'ATA', '010', 'Antarctica',                               'APAC', true),
    ('AR', 'ARG', '032', 'Argentina',                                'AMER', true),
    ('AS', 'ASM', '016', 'American Samoa',                           'APAC', true),
    ('AT', 'AUT', '040', 'Austria',                                  'EMEA', true),
    ('AU', 'AUS', '036', 'Australia',                                'APAC', true),
    ('AW', 'ABW', '533', 'Aruba',                                    'AMER', true),
    ('AX', 'ALA', '248', 'Aland Islands',                            'EMEA', true),
    ('AZ', 'AZE', '031', 'Azerbaijan',                               'EMEA', true),
    ('BA', 'BIH', '070', 'Bosnia and Herzegovina',                   'EMEA', true),
    ('BB', 'BRB', '052', 'Barbados',                                 'AMER', true),
    ('BD', 'BGD', '050', 'Bangladesh',                               'APAC', true),
    ('BE', 'BEL', '056', 'Belgium',                                  'EMEA', true),
    ('BF', 'BFA', '854', 'Burkina Faso',                             'EMEA', true),
    ('BG', 'BGR', '100', 'Bulgaria',                                 'EMEA', true),
    ('BH', 'BHR', '048', 'Bahrain',                                  'EMEA', true),
    ('BI', 'BDI', '108', 'Burundi',                                  'EMEA', true),
    ('BJ', 'BEN', '204', 'Benin',                                    'EMEA', true),
    ('BL', 'BLM', '652', 'Saint Barthelemy',                         'AMER', true),
    ('BM', 'BMU', '060', 'Bermuda',                                  'AMER', true),
    ('BN', 'BRN', '096', 'Brunei Darussalam',                        'APAC', true),
    ('BO', 'BOL', '068', 'Bolivia',                                  'AMER', true),
    ('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba',         'AMER', true),
    ('BR', 'BRA', '076', 'Brazil',                                   'AMER', true),
    ('BS', 'BHS', '044', 'Bahamas',                                  'AMER', true),
    ('BT', 'BTN', '064', 'Bhutan',                                   'APAC', true),
    ('BV', 'BVT', '074', 'Bouvet Island',                            'EMEA', true),
    ('BW', 'BWA', '072', 'Botswana',                                 'EMEA', true),
    ('BY', 'BLR', '112', 'Belarus',                                  'EMEA', true),
    ('BZ', 'BLZ', '084', 'Belize',                                   'AMER', true),
    ('CA', 'CAN', '124', 'Canada',                                   'AMER', true),
    ('CC', 'CCK', '166', 'Cocos (Keeling) Islands',                  'APAC', true),
    ('CD', 'COD', '180', 'Congo (Democratic Republic of the)',       'EMEA', true),
    ('CF', 'CAF', '140', 'Central African Republic',                 'EMEA', true),
    ('CG', 'COG', '178', 'Congo',                                    'EMEA', true),
    ('CH', 'CHE', '756', 'Switzerland',                              'EMEA', true),
    ('CI', 'CIV', '384', 'Cote d''Ivoire',                           'EMEA', true),
    ('CK', 'COK', '184', 'Cook Islands',                             'APAC', true),
    ('CL', 'CHL', '152', 'Chile',                                    'AMER', true),
    ('CM', 'CMR', '120', 'Cameroon',                                 'EMEA', true),
    ('CN', 'CHN', '156', 'China',                                    'APAC', true),
    ('CO', 'COL', '170', 'Colombia',                                 'AMER', true),
    ('CR', 'CRI', '188', 'Costa Rica',                               'AMER', true),
    ('CU', 'CUB', '192', 'Cuba',                                     'AMER', true),
    ('CV', 'CPV', '132', 'Cabo Verde',                               'EMEA', true),
    ('CW', 'CUW', '531', 'Curacao',                                  'AMER', true),
    ('CX', 'CXR', '162', 'Christmas Island',                         'APAC', true),
    ('CY', 'CYP', '196', 'Cyprus',                                   'EMEA', true),
    ('CZ', 'CZE', '203', 'Czechia',                                  'EMEA', true),
    ('DE', 'DEU', '276', 'Germany',                                  'EMEA', true),
    ('DJ', 'DJI', '262', 'Djibouti',                                 'EMEA', true),
    ('DK', 'DNK', '208', 'Denmark',                                  'EMEA', true),
    ('DM', 'DMA', '212', 'Dominica',                                 'AMER', true),
    ('DO', 'DOM', '214', 'Dominican Republic',                       'AMER', true),
    ('DZ', 'DZA', '012', 'Algeria',                                  'EMEA', true),
    ('EC', 'ECU', '218', 'Ecuador',                                  'AMER', true),
    ('EE', 'EST', '233', 'Estonia',                                  'EMEA', true),
    ('EG', 'EGY', '818', 'Egypt',                                    'EMEA', true),
    ('EH', 'ESH', '732', 'Western Sahara',                           'EMEA', true),
    ('ER', 'ERI', '232', 'Eritrea',                                  'EMEA', true),
    ('ES', 'ESP', '724', 'Spain',                                    'EMEA', true),
    ('ET', 'ETH', '231', 'Ethiopia',                                 'EMEA', true),
    ('FI', 'FIN', '246', 'Finland',                                  'EMEA', true),
    ('FJ', 'FJI', '242', 'Fiji',                                     'APAC', true),
    ('FK', 'FLK', '238', 'Falkland Islands (Malvinas)',              'AMER', true),
    ('FM', 'FSM', '583', 'Micronesia (Federated States of)',         'APAC', true),
    ('FO', 'FRO', '234', 'Faroe Islands',                            'EMEA', true),
    ('FR', 'FRA', '250', 'France',                                   'EMEA', true),
    ('GA', 'GAB', '266', 'Gabon',                                    'EMEA', true),
    ('GB', 'GBR', '826', 'United Kingdom',                           'EMEA', true),
    ('GD', 'GRD', '308', 'Grenada',                                  'AMER', true),
    ('GE', 'GEO', '268', 'Georgia',                                  'EMEA', true),
    ('GF', 'GUF', '254', 'French Guiana',                            'AMER', true),
    ('GG', 'GGY', '831', 'Guernsey',                                 'EMEA', true),
    ('GH', 'GHA', '288', 'Ghana',                                    'EMEA', true),
    ('GI', 'GIB', '292', 'Gibraltar',                                'EMEA', true),
    ('GL', 'GRL', '304', 'Greenland',                                'AMER', true),
    ('GM', 'GMB', '270', 'Gambia',                                   'EMEA', true),
    ('GN', 'GIN', '324', 'Guinea',                                   'EMEA', true),
    ('GP', 'GLP', '312', 'Guadeloupe',                               'AMER', true),
    ('GQ', 'GNQ', '226', 'Equatorial Guinea',                        'EMEA', true),
    ('GR', 'GRC', '300', 'Greece',                                   'EMEA', true),
    ('GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', 'AMER', true),
    ('GT', 'GTM', '320', 'Guatemala',                                'AMER', true),
    ('GU', 'GUM', '316', 'Guam',                                     'APAC', true),
    ('GW', 'GNB', '624', 'Guinea-Bissau',                            'EMEA', true),
    ('GY', 'GUY', '328', 'Guyana',                                   'AMER', true),
    ('HK', 'HKG', '344', 'Hong Kong',                                'APAC', true),
    ('HM', 'HMD', '334', 'Heard Island and McDonald Islands',        'APAC', true),
    ('HN', 'HND', '340', 'Honduras',                                 'AMER', true),
    ('HR', 'HRV', '191', 'Croatia',                                  'EMEA', true),
    ('HT', 'HTI', '332', 'Haiti',                                    'AMER', true),
    ('HU', 'HUN', '348', 'Hungary',                                  'EMEA', true),
    ('ID', 'IDN', '360', 'Indonesia',                                'APAC', true),
    ('IE', 'IRL', '372', 'Ireland',                                  'EMEA', true),
    ('IL', 'ISR', '376', 'Israel',                                   'EMEA', true),
    ('IM', 'IMN', '833', 'Isle of Man',                              'EMEA', true),
    ('IN', 'IND', '356', 'India',                                    'APAC', true),
    ('IO', 'IOT', '086', 'British Indian Ocean Territory',           'APAC', true),
    ('IQ', 'IRQ', '368', 'Iraq',                                     'EMEA', true),
    ('IR', 'IRN', '364', 'Iran (Islamic Republic of)',               'EMEA', true),
    ('IS', 'ISL', '352', 'Iceland',                                  'EMEA', true),
    ('IT', 'ITA', '380', 'Italy',                                    'EMEA', true),
    ('JE', 'JEY', '832', 'Jersey',                                   'EMEA', true),
    ('JM', 'JAM', '388', 'Jamaica',                                  'AMER', true),
    ('JO', 'JOR', '400', 'Jordan',                                   'EMEA', true),
    ('JP', 'JPN', '392', 'Japan',                                    'APAC', true),
    ('KE', 'KEN', '404', 'Kenya',                                    'EMEA', true),
    ('KG', 'KGZ', '417', 'Kyrgyzstan',                               'APAC', true),
    ('KH', 'KHM', '116', 'Cambodia',                                 'APAC', true),
    ('KI', 'KIR', '296', 'Kiribati',                                 'APAC', true),
    ('KM', 'COM', '174', 'Comoros',                                  'EMEA', true),
    ('KN', 'KNA', '659', 'Saint Kitts and Nevis',                    'AMER', true),
    ('KP', 'PRK', '408', 'Korea (Democratic People''s Republic of)', 'APAC', true),
    ('KR', 'KOR', '410', 'Korea (Republic of)',                      'APAC', true),
    ('KW', 'KWT', '414', 'Kuwait',                                   'EMEA', true),
    ('KY', 'CYM', '136', 'Cayman Islands',                           'AMER', true),
    ('KZ', 'KAZ', '398', 'Kazakhstan',                               'APAC', true),
    ('LA', 'LAO', '418', 'Lao People''s Democratic Republic',        'APAC', true),
    ('LB', 'LBN', '422', 'Lebanon',                                  'EMEA', true),
    ('LC', 'LCA', '662', 'Saint Lucia',                              'AMER', true),
    ('LI', 'LIE', '438', 'Liechtenstein',                            'EMEA', true),
    ('LK', 'LKA', '144', 'Sri Lanka',                                'APAC', true),
    ('LR', 'LBR', '430', 'Liberia',                                  'EMEA', true),
    ('LS', 'LSO', '426', 'Lesotho',                                  'EMEA', true),
    ('LT', 'LTU', '440', 'Lithuania',                                'EMEA', true),
    ('LU', 'LUX', '442', 'Luxembourg',                               'EMEA', true),
    ('LV', 'LVA', '428', 'Latvia',                                   'EMEA', true),
    ('LY', 'LBY', '434', 'Libya',                                    'EMEA', true),
    ('MA', 'MAR', '504', 'Morocco',                                  'EMEA', true),
    ('MC', 'MCO', '492', 'Monaco',                                   'EMEA', true),
    ('MD', 'MDA', '498', 'Moldova (Republic of)',                    'EMEA', true),
    ('ME', 'MNE', '499', 'Montenegro',                               'EMEA', true),
    ('MF', 'MAF', '663', 'Saint Martin (French part)',               'AMER', true),
    ('MG', 'MDG', '450', 'Madagascar',                               'EMEA', true),
    ('MH', 'MHL', '584', 'Marshall Islands',                         'APAC', true),
    ('MK', 'MKD', '807', 'North Macedonia',                          'EMEA', true),
    ('ML', 'MLI', '466', 'Mali',                                     'EMEA', true),
    ('MM', 'MMR', '104', 'Myanmar',                                  'APAC', true),
    ('MN', 'MNG', '496', 'Mongolia',                                 'APAC', true),
    ('MO', 'MAC', '446', 'Macao',                                    'APAC', true),
    ('MP', 'MNP', '580', 'Northern Mariana Islands',                 'APAC', true),
    ('MQ', 'MTQ', '474', 'Martinique',                               'AMER', true),
    ('MR', 'MRT', '478', 'Mauritania',                               'EMEA', true),
    ('MS', 'MSR', '500', 'Montserrat',                               'AMER', true),
    ('MT', 'MLT', '470', 'Malta',                                    'EMEA', true),
    ('MU', 'MUS', '480', 'Mauritius',                                'EMEA', true),
    ('MV', 'MDV', '462', 'Maldives',                                 'APAC', true),
    ('MW', 'MWI', '454', 'Malawi',                                   'EMEA', true),
    ('MX', 'MEX', '484', 'Mexico',                                   'AMER', true),
    ('MY', 'MYS', '458', 'Malaysia',                                 'APAC', true),
    ('MZ', 'MOZ', '508', 'Mozambique',                               'EMEA', true),
    ('NA', 'NAM', '516', 'Namibia',                                  'EMEA', true),
    ('NC', 'NCL', '540', 'New Caledonia',                            'APAC', true),
    ('NE', 'NER', '562', 'Niger',                                    'EMEA', true),
    ('NF', 'NFK', '574', 'Norfolk Island',                           'APAC', true),
    ('NG', 'NGA', '566', 'Nigeria',                                  'EMEA', true),
    ('NI', 'NIC', '558', 'Nicaragua',                                'AMER', true),
    ('NL', 'NLD', '528', 'Netherlands',                              'EMEA', true),
    ('NO', 'NOR', '578', 'Norway',                                   'EMEA', true),
    ('NP', 'NPL', '524', 'Nepal',                                    'APAC', true),
    ('NR', 'NRU', '520', 'Nauru',                                    'APAC', true),
    ('NU', 'NIU', '570', 'Niue',                                     'APAC', true),
    ('NZ', 'NZL', '554', 'New Zealand',                              'APAC', true),
    ('OM', 'OMN', '512', 'Oman',                                     'EMEA', true),
    ('PA', 'PAN', '591', 'Panama',                                   'AMER', true),
    ('PE', 'PER', '604', 'Peru',                                     'AMER', true),
    ('PF', 'PYF', '258', 'French Polynesia',                         'APAC', true),
    ('PG', 'PNG', '598', 'Papua New Guinea',                         'APAC', true),
    ('PH', 'PHL', '608', 'Philippines',                              'APAC', true),
    ('PK', 'PAK', '586', 'Pakistan',                                 'APAC', true),
    ('PL', 'POL', '616', 'Poland',                                   'EMEA', true),
    ('PM', 'SPM', '666', 'Saint Pierre and Miquelon',                'AMER', true),
    ('PN', 'PCN', '612', 'Pitcairn',                                 'APAC', true),
    ('PR', 'PRI', '630', 'Puerto Rico',                              'AMER', true),
    ('PS', 'PSE', '275', 'Palestine, State of',                      'EMEA', true),
    ('PT', 'PRT', '620', 'Portugal',                                 'EMEA', true),
    ('PW', 'PLW', '585', 'Palau',                                    'APAC', true),
    ('PY', 'PRY', '600', 'Paraguay',                                 'AMER', true),
    ('QA', 'QAT', '634', 'Qatar',                                    'EMEA', true),
    ('RE', 'REU', '638', 'Reunion',                                  'EMEA', true),
    ('RO', 'ROU', '642', 'Romania',                                  'EMEA', true),
    ('RS', 'SRB', '688', 'Serbia',                                   'EMEA', true),
    ('RU', 'RUS', '643', 'Russian Federation',                       'EMEA', true),
    ('RW', 'RWA', '646', 'Rwanda',                                   'EMEA', true),
    ('SA', 'SAU', '682', 'Saudi Arabia',                             'EMEA', true),
    ('SB', 'SLB', '090', 'Solomon Islands',                          'APAC', true),
    ('SC', 'SYC', '690', 'Seychelles',                               'EMEA', true),
    ('SD', 'SDN', '729', 'Sudan',                                    'EMEA', true),
    ('SE', 'SWE', '752', 'Sweden',                                   'EMEA', true),
    ('SG', 'SGP', '702', 'Singapore',                                'APAC', true),
    ('SH', 'SHN', '654', 'Saint Helena, Ascension and Tristan da Cunha', 'EMEA', true),
    ('SI', 'SVN', '705', 'Slovenia',                                 'EMEA', true),
    ('SJ', 'SJM', '744', 'Svalbard and Jan Mayen',                   'EMEA', true),
    ('SK', 'SVK', '703', 'Slovakia',                                 'EMEA', true),
    ('SL', 'SLE', '694', 'Sierra Leone',                             'EMEA', true),
    ('SM', 'SMR', '674', 'San Marino',                               'EMEA', true),
    ('SN', 'SEN', '686', 'Senegal',                                  'EMEA', true),
    ('SO', 'SOM', '706', 'Somalia',                                  'EMEA', true),
    ('SR', 'SUR', '740', 'Suriname',                                 'AMER', true),
    ('SS', 'SSD', '728', 'South Sudan',                              'EMEA', true),
    ('ST', 'STP', '678', 'Sao Tome and Principe',                    'EMEA', true),
    ('SV', 'SLV', '222', 'El Salvador',                              'AMER', true),
    ('SX', 'SXM', '534', 'Sint Maarten (Dutch part)',                'AMER', true),
    ('SY', 'SYR', '760', 'Syrian Arab Republic',                     'EMEA', true),
    ('SZ', 'SWZ', '748', 'Eswatini',                                 'EMEA', true),
    ('TC', 'TCA', '796', 'Turks and Caicos Islands',                 'AMER', true),
    ('TD', 'TCD', '148', 'Chad',                                     'EMEA', true),
    ('TF', 'ATF', '260', 'French Southern Territories',              'EMEA', true),
    ('TG', 'TGO', '768', 'Togo',                                     'EMEA', true),
    ('TH', 'THA', '764', 'Thailand',                                 'THAILAND', true),
    ('TJ', 'TJK', '762', 'Tajikistan',                               'APAC', true),
    ('TK', 'TKL', '772', 'Tokelau',                                  'APAC', true),
    ('TL', 'TLS', '626', 'Timor-Leste',                              'APAC', true),
    ('TM', 'TKM', '795', 'Turkmenistan',                             'APAC', true),
    ('TN', 'TUN', '788', 'Tunisia',                                  'EMEA', true),
    ('TO', 'TON', '776', 'Tonga',                                    'APAC', true),
    ('TR', 'TUR', '792', 'Turkiye',                                  'EMEA', true),
    ('TT', 'TTO', '780', 'Trinidad and Tobago',                      'AMER', true),
    ('TV', 'TUV', '798', 'Tuvalu',                                   'APAC', true),
    ('TW', 'TWN', '158', 'Taiwan, Province of China',                'APAC', true),
    ('TZ', 'TZA', '834', 'Tanzania, United Republic of',             'EMEA', true),
    ('UA', 'UKR', '804', 'Ukraine',                                  'EMEA', true),
    ('UG', 'UGA', '800', 'Uganda',                                   'EMEA', true),
    ('UM', 'UMI', '581', 'United States Minor Outlying Islands',     'AMER', true),
    ('US', 'USA', '840', 'United States of America',                 'AMER', true),
    ('UY', 'URY', '858', 'Uruguay',                                  'AMER', true),
    ('UZ', 'UZB', '860', 'Uzbekistan',                               'APAC', true),
    ('VA', 'VAT', '336', 'Holy See',                                 'EMEA', true),
    ('VC', 'VCT', '670', 'Saint Vincent and the Grenadines',         'AMER', true),
    ('VE', 'VEN', '862', 'Venezuela (Bolivarian Republic of)',       'AMER', true),
    ('VG', 'VGB', '092', 'Virgin Islands (British)',                 'AMER', true),
    ('VI', 'VIR', '850', 'Virgin Islands (U.S.)',                    'AMER', true),
    ('VN', 'VNM', '704', 'Viet Nam',                                 'APAC', true),
    ('VU', 'VUT', '548', 'Vanuatu',                                  'APAC', true),
    ('WF', 'WLF', '876', 'Wallis and Futuna',                        'APAC', true),
    ('WS', 'WSM', '882', 'Samoa',                                    'APAC', true),
    ('YE', 'YEM', '887', 'Yemen',                                    'EMEA', true),
    ('YT', 'MYT', '175', 'Mayotte',                                  'EMEA', true),
    ('ZA', 'ZAF', '710', 'South Africa',                             'EMEA', true),
    ('ZM', 'ZMB', '894', 'Zambia',                                   'EMEA', true),
    ('ZW', 'ZWE', '716', 'Zimbabwe',                                 'EMEA', true)
ON CONFLICT (code) DO NOTHING;
