-- Phase 0 reference data: ISO-3166-1 alpha-2 countries.
--
-- Schema: investment__countries (id UUID PK, iso_code CHAR(2) UNIQUE, name,
-- region_id UUID FK to investment__regions, is_active). The region_id is
-- resolved via JOIN on the region's `code`.
--
-- Region mapping: TH is pinned to THAILAND for domestic-scope queries; every
-- other country resolves to APAC, EMEA, or AMER. The cross-cutting buckets
-- (GLOBAL, EMERGING, DEVELOPED) are populated at the fund / instrument layer
-- in a later phase.

INSERT INTO investment__countries (iso_code, name, region_id, is_active)
SELECT v.iso_code, v.name, r.id, true
FROM (VALUES
    ('AD', 'Andorra',                                              'EMEA'),
    ('AE', 'United Arab Emirates',                                 'EMEA'),
    ('AF', 'Afghanistan',                                          'APAC'),
    ('AG', 'Antigua and Barbuda',                                  'AMER'),
    ('AI', 'Anguilla',                                             'AMER'),
    ('AL', 'Albania',                                              'EMEA'),
    ('AM', 'Armenia',                                              'EMEA'),
    ('AO', 'Angola',                                               'EMEA'),
    ('AQ', 'Antarctica',                                           'APAC'),
    ('AR', 'Argentina',                                            'AMER'),
    ('AS', 'American Samoa',                                       'APAC'),
    ('AT', 'Austria',                                              'EMEA'),
    ('AU', 'Australia',                                            'APAC'),
    ('AW', 'Aruba',                                                'AMER'),
    ('AX', 'Aland Islands',                                        'EMEA'),
    ('AZ', 'Azerbaijan',                                           'EMEA'),
    ('BA', 'Bosnia and Herzegovina',                               'EMEA'),
    ('BB', 'Barbados',                                             'AMER'),
    ('BD', 'Bangladesh',                                           'APAC'),
    ('BE', 'Belgium',                                              'EMEA'),
    ('BF', 'Burkina Faso',                                         'EMEA'),
    ('BG', 'Bulgaria',                                             'EMEA'),
    ('BH', 'Bahrain',                                              'EMEA'),
    ('BI', 'Burundi',                                              'EMEA'),
    ('BJ', 'Benin',                                                'EMEA'),
    ('BL', 'Saint Barthelemy',                                     'AMER'),
    ('BM', 'Bermuda',                                              'AMER'),
    ('BN', 'Brunei Darussalam',                                    'APAC'),
    ('BO', 'Bolivia',                                              'AMER'),
    ('BQ', 'Bonaire, Sint Eustatius and Saba',                     'AMER'),
    ('BR', 'Brazil',                                               'AMER'),
    ('BS', 'Bahamas',                                              'AMER'),
    ('BT', 'Bhutan',                                               'APAC'),
    ('BV', 'Bouvet Island',                                        'EMEA'),
    ('BW', 'Botswana',                                             'EMEA'),
    ('BY', 'Belarus',                                              'EMEA'),
    ('BZ', 'Belize',                                               'AMER'),
    ('CA', 'Canada',                                               'AMER'),
    ('CC', 'Cocos (Keeling) Islands',                              'APAC'),
    ('CD', 'Congo (Democratic Republic of the)',                   'EMEA'),
    ('CF', 'Central African Republic',                             'EMEA'),
    ('CG', 'Congo',                                                'EMEA'),
    ('CH', 'Switzerland',                                          'EMEA'),
    ('CI', 'Cote d''Ivoire',                                       'EMEA'),
    ('CK', 'Cook Islands',                                         'APAC'),
    ('CL', 'Chile',                                                'AMER'),
    ('CM', 'Cameroon',                                             'EMEA'),
    ('CN', 'China',                                                'APAC'),
    ('CO', 'Colombia',                                             'AMER'),
    ('CR', 'Costa Rica',                                           'AMER'),
    ('CU', 'Cuba',                                                 'AMER'),
    ('CV', 'Cabo Verde',                                           'EMEA'),
    ('CW', 'Curacao',                                              'AMER'),
    ('CX', 'Christmas Island',                                     'APAC'),
    ('CY', 'Cyprus',                                               'EMEA'),
    ('CZ', 'Czechia',                                              'EMEA'),
    ('DE', 'Germany',                                              'EMEA'),
    ('DJ', 'Djibouti',                                             'EMEA'),
    ('DK', 'Denmark',                                              'EMEA'),
    ('DM', 'Dominica',                                             'AMER'),
    ('DO', 'Dominican Republic',                                   'AMER'),
    ('DZ', 'Algeria',                                              'EMEA'),
    ('EC', 'Ecuador',                                              'AMER'),
    ('EE', 'Estonia',                                              'EMEA'),
    ('EG', 'Egypt',                                                'EMEA'),
    ('EH', 'Western Sahara',                                       'EMEA'),
    ('ER', 'Eritrea',                                              'EMEA'),
    ('ES', 'Spain',                                                'EMEA'),
    ('ET', 'Ethiopia',                                             'EMEA'),
    ('FI', 'Finland',                                              'EMEA'),
    ('FJ', 'Fiji',                                                 'APAC'),
    ('FK', 'Falkland Islands (Malvinas)',                          'AMER'),
    ('FM', 'Micronesia (Federated States of)',                     'APAC'),
    ('FO', 'Faroe Islands',                                        'EMEA'),
    ('FR', 'France',                                               'EMEA'),
    ('GA', 'Gabon',                                                'EMEA'),
    ('GB', 'United Kingdom',                                       'EMEA'),
    ('GD', 'Grenada',                                              'AMER'),
    ('GE', 'Georgia',                                              'EMEA'),
    ('GF', 'French Guiana',                                        'AMER'),
    ('GG', 'Guernsey',                                             'EMEA'),
    ('GH', 'Ghana',                                                'EMEA'),
    ('GI', 'Gibraltar',                                            'EMEA'),
    ('GL', 'Greenland',                                            'AMER'),
    ('GM', 'Gambia',                                               'EMEA'),
    ('GN', 'Guinea',                                               'EMEA'),
    ('GP', 'Guadeloupe',                                           'AMER'),
    ('GQ', 'Equatorial Guinea',                                    'EMEA'),
    ('GR', 'Greece',                                               'EMEA'),
    ('GS', 'South Georgia and the South Sandwich Islands',         'AMER'),
    ('GT', 'Guatemala',                                            'AMER'),
    ('GU', 'Guam',                                                 'APAC'),
    ('GW', 'Guinea-Bissau',                                        'EMEA'),
    ('GY', 'Guyana',                                               'AMER'),
    ('HK', 'Hong Kong',                                            'APAC'),
    ('HM', 'Heard Island and McDonald Islands',                    'APAC'),
    ('HN', 'Honduras',                                             'AMER'),
    ('HR', 'Croatia',                                              'EMEA'),
    ('HT', 'Haiti',                                                'AMER'),
    ('HU', 'Hungary',                                              'EMEA'),
    ('ID', 'Indonesia',                                            'APAC'),
    ('IE', 'Ireland',                                              'EMEA'),
    ('IL', 'Israel',                                               'EMEA'),
    ('IM', 'Isle of Man',                                          'EMEA'),
    ('IN', 'India',                                                'APAC'),
    ('IO', 'British Indian Ocean Territory',                       'APAC'),
    ('IQ', 'Iraq',                                                 'EMEA'),
    ('IR', 'Iran (Islamic Republic of)',                           'EMEA'),
    ('IS', 'Iceland',                                              'EMEA'),
    ('IT', 'Italy',                                                'EMEA'),
    ('JE', 'Jersey',                                               'EMEA'),
    ('JM', 'Jamaica',                                              'AMER'),
    ('JO', 'Jordan',                                               'EMEA'),
    ('JP', 'Japan',                                                'APAC'),
    ('KE', 'Kenya',                                                'EMEA'),
    ('KG', 'Kyrgyzstan',                                           'APAC'),
    ('KH', 'Cambodia',                                             'APAC'),
    ('KI', 'Kiribati',                                             'APAC'),
    ('KM', 'Comoros',                                              'EMEA'),
    ('KN', 'Saint Kitts and Nevis',                                'AMER'),
    ('KP', 'Korea (Democratic People''s Republic of)',             'APAC'),
    ('KR', 'Korea (Republic of)',                                  'APAC'),
    ('KW', 'Kuwait',                                               'EMEA'),
    ('KY', 'Cayman Islands',                                       'AMER'),
    ('KZ', 'Kazakhstan',                                           'APAC'),
    ('LA', 'Lao People''s Democratic Republic',                    'APAC'),
    ('LB', 'Lebanon',                                              'EMEA'),
    ('LC', 'Saint Lucia',                                          'AMER'),
    ('LI', 'Liechtenstein',                                        'EMEA'),
    ('LK', 'Sri Lanka',                                            'APAC'),
    ('LR', 'Liberia',                                              'EMEA'),
    ('LS', 'Lesotho',                                              'EMEA'),
    ('LT', 'Lithuania',                                            'EMEA'),
    ('LU', 'Luxembourg',                                           'EMEA'),
    ('LV', 'Latvia',                                               'EMEA'),
    ('LY', 'Libya',                                                'EMEA'),
    ('MA', 'Morocco',                                              'EMEA'),
    ('MC', 'Monaco',                                               'EMEA'),
    ('MD', 'Moldova (Republic of)',                                'EMEA'),
    ('ME', 'Montenegro',                                           'EMEA'),
    ('MF', 'Saint Martin (French part)',                           'AMER'),
    ('MG', 'Madagascar',                                           'EMEA'),
    ('MH', 'Marshall Islands',                                     'APAC'),
    ('MK', 'North Macedonia',                                      'EMEA'),
    ('ML', 'Mali',                                                 'EMEA'),
    ('MM', 'Myanmar',                                              'APAC'),
    ('MN', 'Mongolia',                                             'APAC'),
    ('MO', 'Macao',                                                'APAC'),
    ('MP', 'Northern Mariana Islands',                             'APAC'),
    ('MQ', 'Martinique',                                           'AMER'),
    ('MR', 'Mauritania',                                           'EMEA'),
    ('MS', 'Montserrat',                                           'AMER'),
    ('MT', 'Malta',                                                'EMEA'),
    ('MU', 'Mauritius',                                            'EMEA'),
    ('MV', 'Maldives',                                             'APAC'),
    ('MW', 'Malawi',                                               'EMEA'),
    ('MX', 'Mexico',                                               'AMER'),
    ('MY', 'Malaysia',                                             'APAC'),
    ('MZ', 'Mozambique',                                           'EMEA'),
    ('NA', 'Namibia',                                              'EMEA'),
    ('NC', 'New Caledonia',                                        'APAC'),
    ('NE', 'Niger',                                                'EMEA'),
    ('NF', 'Norfolk Island',                                       'APAC'),
    ('NG', 'Nigeria',                                              'EMEA'),
    ('NI', 'Nicaragua',                                            'AMER'),
    ('NL', 'Netherlands',                                          'EMEA'),
    ('NO', 'Norway',                                               'EMEA'),
    ('NP', 'Nepal',                                                'APAC'),
    ('NR', 'Nauru',                                                'APAC'),
    ('NU', 'Niue',                                                 'APAC'),
    ('NZ', 'New Zealand',                                          'APAC'),
    ('OM', 'Oman',                                                 'EMEA'),
    ('PA', 'Panama',                                               'AMER'),
    ('PE', 'Peru',                                                 'AMER'),
    ('PF', 'French Polynesia',                                     'APAC'),
    ('PG', 'Papua New Guinea',                                     'APAC'),
    ('PH', 'Philippines',                                          'APAC'),
    ('PK', 'Pakistan',                                             'APAC'),
    ('PL', 'Poland',                                               'EMEA'),
    ('PM', 'Saint Pierre and Miquelon',                            'AMER'),
    ('PN', 'Pitcairn',                                             'APAC'),
    ('PR', 'Puerto Rico',                                          'AMER'),
    ('PS', 'Palestine, State of',                                  'EMEA'),
    ('PT', 'Portugal',                                             'EMEA'),
    ('PW', 'Palau',                                                'APAC'),
    ('PY', 'Paraguay',                                             'AMER'),
    ('QA', 'Qatar',                                                'EMEA'),
    ('RE', 'Reunion',                                              'EMEA'),
    ('RO', 'Romania',                                              'EMEA'),
    ('RS', 'Serbia',                                               'EMEA'),
    ('RU', 'Russian Federation',                                   'EMEA'),
    ('RW', 'Rwanda',                                               'EMEA'),
    ('SA', 'Saudi Arabia',                                         'EMEA'),
    ('SB', 'Solomon Islands',                                      'APAC'),
    ('SC', 'Seychelles',                                           'EMEA'),
    ('SD', 'Sudan',                                                'EMEA'),
    ('SE', 'Sweden',                                               'EMEA'),
    ('SG', 'Singapore',                                            'APAC'),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha',         'EMEA'),
    ('SI', 'Slovenia',                                             'EMEA'),
    ('SJ', 'Svalbard and Jan Mayen',                               'EMEA'),
    ('SK', 'Slovakia',                                             'EMEA'),
    ('SL', 'Sierra Leone',                                         'EMEA'),
    ('SM', 'San Marino',                                           'EMEA'),
    ('SN', 'Senegal',                                              'EMEA'),
    ('SO', 'Somalia',                                              'EMEA'),
    ('SR', 'Suriname',                                             'AMER'),
    ('SS', 'South Sudan',                                          'EMEA'),
    ('ST', 'Sao Tome and Principe',                                'EMEA'),
    ('SV', 'El Salvador',                                          'AMER'),
    ('SX', 'Sint Maarten (Dutch part)',                            'AMER'),
    ('SY', 'Syrian Arab Republic',                                 'EMEA'),
    ('SZ', 'Eswatini',                                             'EMEA'),
    ('TC', 'Turks and Caicos Islands',                             'AMER'),
    ('TD', 'Chad',                                                 'EMEA'),
    ('TF', 'French Southern Territories',                          'EMEA'),
    ('TG', 'Togo',                                                 'EMEA'),
    ('TH', 'Thailand',                                             'THAILAND'),
    ('TJ', 'Tajikistan',                                           'APAC'),
    ('TK', 'Tokelau',                                              'APAC'),
    ('TL', 'Timor-Leste',                                          'APAC'),
    ('TM', 'Turkmenistan',                                         'APAC'),
    ('TN', 'Tunisia',                                              'EMEA'),
    ('TO', 'Tonga',                                                'APAC'),
    ('TR', 'Turkiye',                                              'EMEA'),
    ('TT', 'Trinidad and Tobago',                                  'AMER'),
    ('TV', 'Tuvalu',                                               'APAC'),
    ('TW', 'Taiwan, Province of China',                            'APAC'),
    ('TZ', 'Tanzania, United Republic of',                         'EMEA'),
    ('UA', 'Ukraine',                                              'EMEA'),
    ('UG', 'Uganda',                                               'EMEA'),
    ('UM', 'United States Minor Outlying Islands',                 'AMER'),
    ('US', 'United States of America',                             'AMER'),
    ('UY', 'Uruguay',                                              'AMER'),
    ('UZ', 'Uzbekistan',                                           'APAC'),
    ('VA', 'Holy See',                                             'EMEA'),
    ('VC', 'Saint Vincent and the Grenadines',                     'AMER'),
    ('VE', 'Venezuela (Bolivarian Republic of)',                   'AMER'),
    ('VG', 'Virgin Islands (British)',                             'AMER'),
    ('VI', 'Virgin Islands (U.S.)',                                'AMER'),
    ('VN', 'Viet Nam',                                             'APAC'),
    ('VU', 'Vanuatu',                                              'APAC'),
    ('WF', 'Wallis and Futuna',                                    'APAC'),
    ('WS', 'Samoa',                                                'APAC'),
    ('YE', 'Yemen',                                                'EMEA'),
    ('YT', 'Mayotte',                                              'EMEA'),
    ('ZA', 'South Africa',                                         'EMEA'),
    ('ZM', 'Zambia',                                               'EMEA'),
    ('ZW', 'Zimbabwe',                                             'EMEA')
) AS v(iso_code, name, region_code)
JOIN investment__regions r ON r.code = v.region_code
ON CONFLICT (iso_code) DO NOTHING;
